---
name: Okancan
surname: Balcı
address: "Ankara / Turkey"
phone: +90 505 807 39 29
www: soon-to-be-filled
email: "okancan.balci@gmail.com"
github: Okancan-Balci
linkedin: okancan-balci
aboutme: "Aspiring Data Scientist"
output: vitae::twentyseconds
---

```{r setup, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```


# Education

```{r}
read.csv(file = "education.csv", header = TRUE) %>% 
  detailed_entries(
    what = degree,
    when = when,
    where = department,
    with = university,
    why = gpa
  )
```

# Technical Stack

```{r}
read_csv2("skills.csv") %>% 
  detailed_entries(
    when = skill,
    why = information
  )
```


# Certificates

```{r}
read_csv2("certificates.csv") %>% 
  detailed_entries(
    when = year,
    what = certificate,
    with = institution,
    why = details
  )
```


# Academic Works

```{r}
read_csv2("academic.csv") %>% 
  detailed_entries(
    when = year,
    what = project,
    with = institution,
    why = info,
    where = context
  )
```


# Personal Projects

```{r}
read_csv2("projects.csv") %>% 
  detailed_entries(
    when = year,
    what = project,
    with = where,
    why = info
  )
```




